### ISSUE TITLE
serialHTMP.println() does not linefeed

### ISSUE THREAD

**Issue by krulkip** [kickshawprogrammer/SerialHTML#1]
Title says issue

**Comment by kickshawprogrammer** [comment]
Not sure why that is. It inherits directly from the Print class which appends a “\r\n” to the text. I’ll take a closer look later after work.

**Comment by krulkip** [comment]
Thank you very much. Its a great piece of coding allowing easy adaptation of the webpage used. I will try with printf which i have not done so far. I tried to copy the print related parts from webserial but that did not work
Bas
    On Wednesday, 21 December 2022, 11:35:33 CET, kickshawprogrammer ***@***.***> wrote:  
 
 


Not sure why that is. It inherits directly from the Print class which appends a “\r\n” to the text. I’ll take a closer look later after work.

**Comment by krulkip** [comment]
Checked with printf and issue is same. 
Then i checked with PC browser and problem solved. So its a phone browser specific issue. iphone

**Comment by kickshawprogrammer** [comment]
I did see a reference to this issue with iPhones from like 2016 or some such. I have been trying to find a resolution. Looking for some kind of socket configuration setting but nothing yet. I’ll continue to look but I’m certain it’s not my code. 

PS: I’m glad you’re liking it otherwise.
